### ISSUE TITLE
Pass more information for account creation

### ISSUE THREAD

**Issue by RayeN** [yola/sitewit#55]
In the scope of this ticket we should:

 - accept optional `mobile_phone` for account creation (service/model)
 - pass real user's email (model). please note that we should use `wl_email` if it's present

related discussion: https://github.com/yola/p-whitelabel/issues/1124

**Comment by stefanor** [comment]
> pass real user's email (model). please note that we should use wl_email if it's present

What I forgot here is that we should only do that for users who explicitly signed up for Sitewit, not every user that gets sitewit analytics.

**Comment by RayeN** [comment]
> who explicitly signed up for Sitewit

Can you please provide more details.  Not sure I understand you.

**Comment by stefanor** [comment]
Never mind, we discussed it in Slack, and you're on the right track here.

**Comment by snitch** [comment]
@ekoval: This issue is now a priority.

**Comment by RayeN** [comment]
Can we please also pass `username` (with the same value we had previously for email:  `<user_id>@yola.yola`?  (now we can do that since SW released their changes already).  And after that update sitewitservice to use a new sitewit client.

**Comment by ekoval** [comment]
Done
